# Generated by Django 4.0.5 on 2022-07-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('icon', models.ImageField(upload_to='clubs/&Y/&m/&d')),
                ('slug', models.SlugField(default='')),
            ],
            options={
                'verbose_name': 'Клуб',
                'verbose_name_plural': 'Клубы',
                'ordering': ['name'],
            },
        ),
    ]
