# Generated by Django 4.0.5 on 2022-07-03 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Имя')),
                ('birthday', models.DateField()),
                ('game_number', models.PositiveSmallIntegerField()),
                ('grip', models.CharField(choices=[('левый', 'левый'), ('правый', 'правый')], max_length=6)),
                ('slug', models.SlugField(max_length=40)),
                ('icon', models.ImageField(upload_to='players/&Y/&m/&d')),
                ('position', models.CharField(choices=[('защитник', 'защитник'), ('нападающий', 'нападающий'), ('вратарь', 'вратарь')], max_length=15)),
                ('games', models.PositiveSmallIntegerField(default=0)),
                ('goals', models.PositiveSmallIntegerField(default=0)),
                ('assists', models.PositiveSmallIntegerField(default=0)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clubs.clubs')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
                'ordering': ['name'],
            },
        ),
    ]
