# Generated by Django 4.0.5 on 2022-07-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='icon',
            field=models.ImageField(upload_to='players/%Y/%m/%d'),
        ),
    ]
